handlers:
  console:
    class : logging.StreamHandler
    formatter: brief
    level   : INFO
    filters: []
    stream  : ext://sys.stdout
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: precise
    mode: a
    filename: run.log
    maxBytes: 1024
    backupCount: 3