agent:
- !!omap
  - name: size
  - resizable: false
- !!omap
  - name: shape
  - resizable: false
- !!omap
  - name: circular
  - resizable: false
- !!omap
  - name: three_circle
  - resizable: false
- !!omap
  - name: orientable
  - resizable: false
- !!omap
  - name: active
  - resizable: false
- !!omap
  - name: goal_reached
  - resizable: false
- !!omap
  - name: mass
  - resizable: false
- !!omap
  - name: radius
  - resizable: false
- !!omap
  - name: r_t
  - resizable: false
- !!omap
  - name: r_s
  - resizable: false
- !!omap
  - name: r_ts
  - resizable: false
- !!omap
  - name: position
  - resizable: false
- !!omap
  - name: velocity
  - resizable: false
- !!omap
  - name: target_velocity
  - resizable: false
- !!omap
  - name: target_direction
  - resizable: false
- !!omap
  - name: force
  - resizable: false
- !!omap
  - name: inertia_rot
  - resizable: false
- !!omap
  - name: angle
  - resizable: false
- !!omap
  - name: angular_velocity
  - resizable: false
- !!omap
  - name: target_angle
  - resizable: false
- !!omap
  - name: target_angular_velocity
  - resizable: false
- !!omap
  - name: torque
  - resizable: false
- !!omap
  - name: position_ls
  - resizable: false
- !!omap
  - name: position_rs
  - resizable: false
- !!omap
  - name: front
  - resizable: false
- !!omap
  - name: tau_adj
  - resizable: false
- !!omap
  - name: tau_rot
  - resizable: false
- !!omap
  - name: k_soc
  - resizable: false
- !!omap
  - name: tau_0
  - resizable: false
- !!omap
  - name: mu
  - resizable: false
- !!omap
  - name: kappa
  - resizable: false
- !!omap
  - name: damping
  - resizable: false
- !!omap
  - name: std_rand_force
  - resizable: false
- !!omap
  - name: std_rand_torque
  - resizable: false
- !!omap
  - name: f_soc_ij_max
  - resizable: false
- !!omap
  - name: f_soc_iw_max
  - resizable: false
- !!omap
  - name: sight_soc
  - resizable: false
- !!omap
  - name: sight_wall
  - resizable: false
- !!omap
  - name: neighbor_radius
  - resizable: false
- !!omap
  - name: neighborhood_size
  - resizable: false
- !!omap
  - name: neighbors
  - resizable: false
- !!omap
  - name: neighbor_distances
  - resizable: false
- !!omap
  - name: neighbor_distances_max
  - resizable: false
