---
# Pyqtgraph graphics arguments
# pyqtgraph.mkPen
# pyqtgraph.mkBrush

circle:
  symbol: "o"
  symbolSize: 2 * radius
  pen: null
  pxMode: false

domain:
  pen: null
  brush: [255, 255, 255, 31]

goal:
  pen: null
  brush: [255, 255, 255, 63]

agent:
  active:
    pen: "w"
    brush: [0, 0, 255, 255]
  inactive:
    pen: null
    brush: [0, 0, 0, 0]
  patient:
    pen: "w"
    brush: [0, 0, 255, 255]
  impatient:
    pen: "w"
    brush: [255, 0, 0, 255]

...