version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: %(asctime)s [%(levelname)s] %(name)s: %(message)s

handlers:
  console:
    class : logging.StreamHandler
    formatter: brief
    level   : INFO
    filters: []
    stream  : ext://sys.stdout
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: precise
    filename: run.log
    maxBytes: 1024
    backupCount: 3