---

# Some resources for writing loggers
# http://victorlin.me/posts/2012/08/26/good-logging-practice-in-python
# https://docs.python.org/2/howto/logging-cookbook.html#logging-cookbook

version: 1
disable_existing_loggers: False


formatters:
  simple:
    format: "%(asctime)s - %(levelname)-8s - %(name)-12s - %(funcName)s: %(message)s"
  plain:
    format: "%(asctime)s - %(levelname)s <%(funcName)s> %(message)s"


handlers:
  console:
    class: "logging.StreamHandler"
    formatter: plain
    level: DEBUG
    stream: "ext://sys.stdout"

  debug_file_handler:
    class: "logging.handlers.RotatingFileHandler"
    formatter: plain
    filename: "debug.log"
    level: DEBUG
    maxBytes: 10485760  # 10 MB
    backupCount: 20
    encoding: "utf8"

  info_file_handler:
    class: "logging.handlers.RotatingFileHandler"
    formatter: plain
    filename: "info.log"
    level: INFO
    maxBytes: 10485760  # 10 MB
    backupCount: 20
    encoding: "utf8"

  error_file_handler:
    class: "logging.handlers.RotatingFileHandler"
    formatter: plain
    filename: "errors.log"
    level: ERROR
    maxBytes: 10485760  # 10 MB
    backupCount: 20
    encoding: "utf8"


loggers:
  my_module:
    level: ERROR
    handlers: [console]
    propagate: no


root:
  level: DEBUG
  handlers: [console, debug_file_handler, info_file_handler, error_file_handler]

...