!!omap
- simulation: !!omap
  - dt_min: !!omap
    - resizable: false
    - graphics: false
  - dt_max: !!omap
    - resizable: false
    - graphics: false
  - time_tot: !!omap
    - resizable: true
    - graphics: false
  - in_goal: !!omap
    - resizable: true
    - graphics: false
- agent: !!omap
  - size: !!omap
    - resizable: false
    - graphics: false
  - shape: !!omap
    - resizable: false
    - graphics: false
  - circular: !!omap
    - resizable: false
    - graphics: false
  - three_circle: !!omap
    - resizable: false
    - graphics: false
  - orientable: !!omap
    - resizable: false
    - graphics: false
  - active: !!omap
    - resizable: true
    - graphics: true
  - goal_reached: !!omap
    - resizable: false
    - graphics: true
  - mass: !!omap
    - resizable: false
    - graphics: false
  - radius: !!omap
    - resizable: false
    - graphics: false
  - r_t: !!omap
    - resizable: false
    - graphics: false
  - r_s: !!omap
    - resizable: false
    - graphics: false
  - r_ts: !!omap
    - resizable: false
    - graphics: false
  - position: !!omap
    - resizable: true
    - graphics: true
  - velocity: !!omap
    - resizable: false
    - graphics: false
  - target_velocity: !!omap
    - resizable: false
    - graphics: false
  - target_direction: !!omap
    - resizable: false
    - graphics: false
  - force: !!omap
    - resizable: false
    - graphics: false
  - inertia_rot: !!omap
    - resizable: false
    - graphics: false
  - angle: !!omap
    - resizable: true
    - graphics: true
  - angular_velocity: !!omap
    - resizable: false
    - graphics: false
  - target_angle: !!omap
    - resizable: false
    - graphics: false
  - target_angular_velocity: !!omap
    - resizable: false
    - graphics: false
  - torque: !!omap
    - resizable: false
    - graphics: false
  - position_ls: !!omap
    - resizable: false
    - graphics: false
  - position_rs: !!omap
    - resizable: false
    - graphics: false
  - front: !!omap
    - resizable: false
    - graphics: false
  - tau_adj: !!omap
    - resizable: false
    - graphics: false
  - tau_rot: !!omap
    - resizable: false
    - graphics: false
  - k_soc: !!omap
    - resizable: false
    - graphics: false
  - tau_0: !!omap
    - resizable: false
    - graphics: false
  - mu: !!omap
    - resizable: false
    - graphics: false
  - kappa: !!omap
    - resizable: false
    - graphics: false
  - damping: !!omap
    - resizable: false
    - graphics: false
  - std_rand_force: !!omap
    - resizable: false
    - graphics: false
  - std_rand_torque: !!omap
    - resizable: false
    - graphics: false
  - f_soc_ij_max: !!omap
    - resizable: false
    - graphics: false
  - f_soc_iw_max: !!omap
    - resizable: false
    - graphics: false
  - sight_soc: !!omap
    - resizable: false
    - graphics: false
  - sight_wall: !!omap
    - resizable: false
    - graphics: false
  - neighbor_radius: !!omap
    - resizable: false
    - graphics: false
  - neighborhood_size: !!omap
    - resizable: false
    - graphics: false
  - neighbors: !!omap
    - resizable: false
    - graphics: false
  - neighbor_distances: !!omap
    - resizable: false
    - graphics: false
  - neighbor_distances_max: !!omap
    - resizable: false
    - graphics: false
