---
# MultiAgentSimulations
# Classes and kwargs
simulations:
  outdoor:
    module: "src.examples.outdoor"
    class: "Outdoor"
    kwargs:
      size: 100
      model: "three_circle"
      body: "adult"
      height: 20.0
      width: 20.0

  hallway:
    module: "src.examples.hallway"
    class: "Hallway"
    kwargs:
      size: 100
      model: "three_circle"
      body: "adult"
      height: 5.0
      width: 20.0

  room_evacuation:
    module: "src.examples.evacuation"
    class: "RoomEvacuation"
    kwargs:
      size: 100
      model: "circular"
      body: "adult"
      height: 20.0
      width: 10.0
      door_width: 1.2
      exit_hall_width: 2.0
      spawn_shape: "circ"

  room_evacuation_game:
    module: "src.examples.evacuation"
    class: "RoomEvacuationGame"
    kwargs:
      size: 300
      model: "circular"
      body: "adult"
      height: 20.0
      width: 10.0
      door_width: 1.2
      exit_hall_width: 2.0
      spawn_shape: "circ"
      t_aset: 200.0


# Qt mappings for the kwargs
# int    -> QSpinBox        [min, max]
# float -> QDoubleSpinBox  [min, max]
# string -> QComboBox       [string,...]
# bool   -> QRadioButton    {true, false}
kwarg_mapping:
  size: [1, 10000]
  model: ["circular", "three_circle"]
  body: ["adult", "male", "female", "child", "eldery"]
  height: [0, 100]
  width: [0, 100]
  door_width: [0, 3]
  exit_hall_width: [0, 10]
  spawn_shape: ["circ", "rect"]
  t_aset: [0, 100000]
...