agent:
- size
- shape
- circular
- three_circle
- orientable
- active
- goal_reached
- mass
- radius
- r_t
- r_s
- r_ts
- position
- velocity
- target_velocity
- target_direction
- force
- inertia_rot
- angle
- angular_velocity
- target_angle
- target_angular_velocity
- torque
- position_ls
- position_rs
- front
- tau_adj
- tau_rot
- k_soc
- tau_0
- mu
- kappa
- damping
- std_rand_force
- std_rand_torque
- f_soc_ij_max
- f_soc_iw_max
- sight_soc
- sight_wall
- neighbor_radius
- neighborhood_size
- neighbors
- neighbor_distances
- neighbor_distances_max
walls:
- params
- cols
- rows
- size
- wall
