# Dependencies should be same as in ``requirements/package.txt``
# Install env with command:
# conda env create python3.x -n crowd3x -f environment.yml

channels:
    - conda-forge
dependencies:
    ## Package
    - setuptools
    - versioneer
    - typing
    - numpy
    - numba
    - scipy
    - scikit-image
    - shapely
    - pandas
    - h5py
    - pyqt
    - pyqtgraph
    - matplotlib
    - bokeh
    - pip:
        ## Package
        - ruamel.yaml
        - scikit-fmm
        - click
        ## Testing
        - pytest
        - pytest-cov
        - pytest-xdist
        - coverage
        - hypothesis
        ## Documentation
        - sphinx
        - sphinx_rtd_theme
        - sphinxcontrib-napoleon
        - sphinxcontrib-bibtex
        - sphinxcontrib-programoutput
        - ghp-import
        - graphviz
