name: crowd34
channels:
    - conda-forge
dependencies:
    # Pyqt is not working properly with Python 3.5.
    - python=3.4
    - numpy
    - numba
    - scipy
    - scikit-image
    - shapely
    - matplotlib
    - pyqt
    - pyqtgraph
    - h5py
    - yaml
    - pandas
    - typing
    - pip:
        - ruamel.yaml
        - scikit-fmm
