# conda env create python3.x -n crowd3x -f environment.yml

channels:
    - conda-forge
dependencies:
    - setuptools
    - versioneer
    - typing
    - numpy
    - numba
    - scipy
    - scikit-image
    - shapely
    - pandas
    - h5py
    - pyqt
    - pyqtgraph
    - matplotlib
    - bokeh
    - pip:
        - ruamel.yaml
        - scikit-fmm
        - click
