name: crowd35
dependencies:
    - python=3.*
    - numpy
    - numba>=28.*
    - scipy
    - scikit-image
    - shapely
    - matplotlib
    - pyqt
    - pyqtgraph
    - h5py
    - yaml
    - ruamel
    - pandas

    - pip:
        - skfmm # scikit-fmm
