# Dependencies should be same as in ``requirements/package.txt``
# Install env with command:
# conda env create python=3.x -n crowd3x -f environment.yml

channels:
    - conda-forge
dependencies:
    ## Package
    - numpy
    - numba
    - scipy
    - scikit-image
    - shapely
    - pandas
    - h5py
    - pyqt
    - pyqtgraph
    - matplotlib
    - bokeh
    ## Dev
    - jupyter
    - pip:
        ## Package
        - versioneer
        - typing
        - sortedcontainers
        - ruamel.yaml
        - scikit-fmm
        - click
        - colorama
        - colorlog
        ## Testing
        - pytest
        - pytest-cov
        - pytest-xdist
        - coverage
        - hypothesis
        - pytest-benchmark
        ## Documentation
        - sphinx
        - sphinx_rtd_theme
#        - sphinxcontrib-programoutput
        - ghp-import
        - graphviz
        ## Dev
        - pip-tools
